export default categoryList = [
    "All",
    "Action",
    "Adventure",
    "Casual",
    "Indie",
    "Multiplayer",
    "Online",
    "Racing",
    "RPG",
    "Simulation",
    "Sports",
    "Strategy",
    "Technology",
];